/**
 * Sample products and SKU variants
 */
exports.seed = async function (knex) {
  await knex('skus').del();
  await knex('products').del();

  // ── Products ──────────────────────────────────────────────────────────────
  await knex('products').insert([
    // Electronics > Smartphones
    {
      id: 1,
      category_id: 10,
      brand_id: 1,
      name: 'TechCore Pulse X12',
      slug: 'techcore-pulse-x12',
      description: 'Flagship smartphone with 6.7" AMOLED display, 5G, and 108 MP camera.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Electronics > Laptops
    {
      id: 2,
      category_id: 11,
      brand_id: 1,
      name: 'TechCore ProBook 15',
      slug: 'techcore-probook-15',
      description: '15.6" laptop with Intel Core i7, 16 GB RAM, and 512 GB SSD.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Electronics > Audio
    {
      id: 3,
      category_id: 12,
      brand_id: 5,
      name: 'SoundWave ANC Pro',
      slug: 'soundwave-anc-pro',
      description: 'Over-ear wireless headphones with active noise cancellation.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Electronics > Cameras
    {
      id: 4,
      category_id: 13,
      brand_id: 6,
      name: 'NovaLens Alpha 7',
      slug: 'novalens-alpha-7',
      description: 'Mirrorless digital camera with 24 MP sensor and 4K video.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Clothing > Men's
    {
      id: 5,
      category_id: 20,
      brand_id: 2,
      name: 'UrbanWear Classic Tee',
      slug: 'urbanwear-classic-tee',
      description: '100% organic cotton crew-neck t-shirt.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Clothing > Women's
    {
      id: 6,
      category_id: 21,
      brand_id: 2,
      name: 'UrbanWear Slim Jogger',
      slug: 'urbanwear-slim-jogger',
      description: 'Tapered slim-fit jogger pants with side pockets.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Clothing > Footwear
    {
      id: 7,
      category_id: 23,
      brand_id: 4,
      name: 'PeakSport TrailRunner',
      slug: 'peaksport-trailrunner',
      description: 'All-terrain trail running shoe with waterproof upper.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Home & Garden > Kitchen
    {
      id: 8,
      category_id: 31,
      brand_id: 3,
      name: 'HomeFirst BlendMaster Pro',
      slug: 'homefirst-blendmaster-pro',
      description: '1500 W professional-grade countertop blender.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Sports > Fitness Equipment
    {
      id: 9,
      category_id: 40,
      brand_id: 4,
      name: 'PeakSport Adjustable Dumbbell Set',
      slug: 'peaksport-adjustable-dumbbell-set',
      description: 'Adjustable dumbbells ranging from 5 to 50 lbs per hand.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Sports > Camping & Hiking
    {
      id: 10,
      category_id: 41,
      brand_id: 4,
      name: 'PeakSport Summit Tent',
      slug: 'peaksport-summit-tent',
      description: '3-season 2-person backpacking tent, ultralight at 1.2 kg.',
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);

  // ── SKUs ──────────────────────────────────────────────────────────────────
  await knex('skus').insert([
    // Product 1: TechCore Pulse X12 — colour variants
    {
      id: 101,
      product_id: 1,
      sku_code: 'TC-PX12-BLK-128',
      attributes: JSON.stringify({ color: 'Midnight Black', storage: '128 GB' }),
      price: 899.99,
      compare_at_price: 999.99,
      stock_quantity: 50,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 102,
      product_id: 1,
      sku_code: 'TC-PX12-SLV-256',
      attributes: JSON.stringify({ color: 'Glacier Silver', storage: '256 GB' }),
      price: 999.99,
      compare_at_price: 1099.99,
      stock_quantity: 35,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 103,
      product_id: 1,
      sku_code: 'TC-PX12-BLU-512',
      attributes: JSON.stringify({ color: 'Ocean Blue', storage: '512 GB' }),
      price: 1099.99,
      compare_at_price: 1199.99,
      stock_quantity: 20,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 2: TechCore ProBook 15 — RAM/storage variants
    {
      id: 201,
      product_id: 2,
      sku_code: 'TC-PB15-16-512',
      attributes: JSON.stringify({ ram: '16 GB', storage: '512 GB SSD' }),
      price: 1199.99,
      compare_at_price: 1399.99,
      stock_quantity: 25,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 202,
      product_id: 2,
      sku_code: 'TC-PB15-32-1TB',
      attributes: JSON.stringify({ ram: '32 GB', storage: '1 TB SSD' }),
      price: 1599.99,
      compare_at_price: 1799.99,
      stock_quantity: 15,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 3: SoundWave ANC Pro — colour variants
    {
      id: 301,
      product_id: 3,
      sku_code: 'SW-ANC-BLK',
      attributes: JSON.stringify({ color: 'Matte Black' }),
      price: 249.99,
      compare_at_price: 299.99,
      stock_quantity: 60,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 302,
      product_id: 3,
      sku_code: 'SW-ANC-WHT',
      attributes: JSON.stringify({ color: 'Pearl White' }),
      price: 249.99,
      compare_at_price: 299.99,
      stock_quantity: 40,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 4: NovaLens Alpha 7 — body only vs kit
    {
      id: 401,
      product_id: 4,
      sku_code: 'NL-A7-BODY',
      attributes: JSON.stringify({ bundle: 'Body Only' }),
      price: 1499.99,
      compare_at_price: 1699.99,
      stock_quantity: 20,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 402,
      product_id: 4,
      sku_code: 'NL-A7-KIT',
      attributes: JSON.stringify({ bundle: 'Kit with 28-70mm Lens' }),
      price: 1899.99,
      compare_at_price: 2099.99,
      stock_quantity: 12,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 5: UrbanWear Classic Tee — size variants
    {
      id: 501,
      product_id: 5,
      sku_code: 'UW-CT-WHT-S',
      attributes: JSON.stringify({ color: 'White', size: 'S' }),
      price: 29.99,
      compare_at_price: null,
      stock_quantity: 100,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 502,
      product_id: 5,
      sku_code: 'UW-CT-WHT-M',
      attributes: JSON.stringify({ color: 'White', size: 'M' }),
      price: 29.99,
      compare_at_price: null,
      stock_quantity: 120,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 503,
      product_id: 5,
      sku_code: 'UW-CT-WHT-L',
      attributes: JSON.stringify({ color: 'White', size: 'L' }),
      price: 29.99,
      compare_at_price: null,
      stock_quantity: 90,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 504,
      product_id: 5,
      sku_code: 'UW-CT-BLK-M',
      attributes: JSON.stringify({ color: 'Black', size: 'M' }),
      price: 29.99,
      compare_at_price: null,
      stock_quantity: 80,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 6: UrbanWear Slim Jogger — size variants
    {
      id: 601,
      product_id: 6,
      sku_code: 'UW-SJ-GRY-S',
      attributes: JSON.stringify({ color: 'Heather Grey', size: 'S' }),
      price: 59.99,
      compare_at_price: 74.99,
      stock_quantity: 50,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 602,
      product_id: 6,
      sku_code: 'UW-SJ-GRY-M',
      attributes: JSON.stringify({ color: 'Heather Grey', size: 'M' }),
      price: 59.99,
      compare_at_price: 74.99,
      stock_quantity: 65,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 603,
      product_id: 6,
      sku_code: 'UW-SJ-NVY-L',
      attributes: JSON.stringify({ color: 'Navy', size: 'L' }),
      price: 59.99,
      compare_at_price: 74.99,
      stock_quantity: 45,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 7: PeakSport TrailRunner — size variants
    {
      id: 701,
      product_id: 7,
      sku_code: 'PS-TR-GRN-9',
      attributes: JSON.stringify({ color: 'Forest Green', size: 'US 9' }),
      price: 119.99,
      compare_at_price: 139.99,
      stock_quantity: 30,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 702,
      product_id: 7,
      sku_code: 'PS-TR-GRN-10',
      attributes: JSON.stringify({ color: 'Forest Green', size: 'US 10' }),
      price: 119.99,
      compare_at_price: 139.99,
      stock_quantity: 28,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 703,
      product_id: 7,
      sku_code: 'PS-TR-GRN-11',
      attributes: JSON.stringify({ color: 'Forest Green', size: 'US 11' }),
      price: 119.99,
      compare_at_price: 139.99,
      stock_quantity: 22,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 8: HomeFirst BlendMaster Pro — single SKU
    {
      id: 801,
      product_id: 8,
      sku_code: 'HF-BMP-SLV',
      attributes: JSON.stringify({ color: 'Silver' }),
      price: 149.99,
      compare_at_price: 179.99,
      stock_quantity: 40,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 9: PeakSport Adjustable Dumbbell Set — single SKU
    {
      id: 901,
      product_id: 9,
      sku_code: 'PS-ADS-PAIR',
      attributes: JSON.stringify({ configuration: 'Pair (2 x 5-50 lbs)' }),
      price: 349.99,
      compare_at_price: 399.99,
      stock_quantity: 25,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 10: PeakSport Summit Tent — colour variant
    {
      id: 1001,
      product_id: 10,
      sku_code: 'PS-ST2P-ORG',
      attributes: JSON.stringify({ color: 'Orange' }),
      price: 299.99,
      compare_at_price: 349.99,
      stock_quantity: 18,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 1002,
      product_id: 10,
      sku_code: 'PS-ST2P-GRN',
      attributes: JSON.stringify({ color: 'Olive Green' }),
      price: 299.99,
      compare_at_price: 349.99,
      stock_quantity: 14,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);
};
