/**
 * Sample promo codes
 */
exports.seed = async function (knex) {
  await knex('promo_codes').del();

  await knex('promo_codes').insert([
    {
      id: 1,
      code: 'WELCOME10',
      description: '10% off for new customers',
      discount_type: 'percentage',
      discount_value: 10.00,
      minimum_order_amount: 0.00,
      maximum_discount_amount: 50.00,
      usage_limit: 1000,
      usage_count: 0,
      is_single_use_per_customer: true,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2025-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 2,
      code: 'SAVE20',
      description: '20% off orders over $100',
      discount_type: 'percentage',
      discount_value: 20.00,
      minimum_order_amount: 100.00,
      maximum_discount_amount: 100.00,
      usage_limit: 500,
      usage_count: 0,
      is_single_use_per_customer: false,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2025-06-30 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 3,
      code: 'FLAT15',
      description: '$15 flat discount on any order',
      discount_type: 'fixed',
      discount_value: 15.00,
      minimum_order_amount: 50.00,
      maximum_discount_amount: null,
      usage_limit: 200,
      usage_count: 0,
      is_single_use_per_customer: true,
      is_active: true,
      starts_at: '2024-03-01 00:00:00',
      expires_at: '2024-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 4,
      code: 'TECH50',
      description: '$50 off electronics orders over $500',
      discount_type: 'fixed',
      discount_value: 50.00,
      minimum_order_amount: 500.00,
      maximum_discount_amount: null,
      usage_limit: 300,
      usage_count: 0,
      is_single_use_per_customer: true,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2025-03-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 5,
      code: 'FREESHIP',
      description: 'Free shipping on any order',
      discount_type: 'free_shipping',
      discount_value: 0.00,
      minimum_order_amount: 0.00,
      maximum_discount_amount: null,
      usage_limit: null,
      usage_count: 0,
      is_single_use_per_customer: false,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2024-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 6,
      code: 'SUMMER30',
      description: '30% off summer sale — limited time',
      discount_type: 'percentage',
      discount_value: 30.00,
      minimum_order_amount: 75.00,
      maximum_discount_amount: 150.00,
      usage_limit: 150,
      usage_count: 0,
      is_single_use_per_customer: true,
      is_active: false,
      starts_at: '2024-06-01 00:00:00',
      expires_at: '2024-08-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 7,
      code: 'STAFF25',
      description: '25% staff discount',
      discount_type: 'percentage',
      discount_value: 25.00,
      minimum_order_amount: 0.00,
      maximum_discount_amount: 200.00,
      usage_limit: null,
      usage_count: 0,
      is_single_use_per_customer: false,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: null,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);
};
